### ISSUE TITLE
Are you planing to improve debugging features for the API Developer?

### ISSUE THREAD

**Issue by sebastiansutter** [ibm-apiconnect/apigateway-experimental#18]
Are there any to plans to introduce some better debugging features with the new gateway experience? Especially, in assemblies that contain a set of policies, it would be helpful to gain some insight into the messages/variables exchanged between the policies and where the errors are actually happening.

**Comment by ozairs** [comment]
We have plans to provide both an enhanced desktop and operational experience:

1. Desktop - provide access to the multi-step probe like capabilities within the API developer toolkit
2. Operations - leverage the DataPower Operations Dashboard to provide a view of transactions, with details, including fine-grain details about performance and memory.
