### ISSUE TITLE
Unable to start the application in API Designer

### ISSUE THREAD

**Issue by sunnygoel8** [ibm-apiconnect/apigateway-experimental#28]
Hi @ozairs ,

I'm getting following error while starting the API in API designer. Could you please help me resolve this ? Please see Docker version details below. It creates an instance of docker compose and immediately exits it. 

**Docker version**

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Error Stack**
Service Local_API's-gw started but did not initialize within the timeout period. Dumping log buffer.
[08/27/17 16:14:05] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.2.0.201612012154 (Agent Core 3.1.0)
[08/27/17 16:14:05] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
2017-08-27T23:14:05.457Z pid:7440 worker:0 INFO supervisor starting (pid 7440)
2017-08-27T23:14:05.461Z pid:7440 worker:0 INFO supervisor reporting metrics to `internal:`
2017-08-27T23:14:05.486Z pid:7440 worker:0 INFO supervisor size set to undefined
2017-08-27T23:14:05.865Z pid:9440 worker:1 [08/27/17 16:14:05] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.2.0.201612012154 (Agent Core 3.1.0)
2017-08-27T23:14:05.947Z pid:9440 worker:1 [08/27/17 16:14:05] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
2017-08-27T23:14:06.658Z pid:9440 worker:1 [apim-lite][info] Starting DataPower API Gateway on port "4001"
2017-08-27T23:14:06.658Z pid:9440 worker:1 [apim-lite][info] Loading project "Local_API's" from "C:\Sunny\API-Connect-Research\Local_API's"
2017-08-27T23:14:07.227Z pid:9440 worker:1 [apim-lite][error] "docker info" exited with non-zero status: 1
2017-08-27T23:14:07.228Z pid:9440 worker:1 [apim-lite][info] Stopping DataPower API Gateway for project "Local_API's"
2017-08-27T23:14:09.254Z pid:7440 worker:0 ERROR supervisor worker id 1 (pid 9440) expected exit with 1
2017-08-27T23:26:04.151Z pid:7440 worker:0 WARN received SIGHUP, restarting workers
[08/27/17 16:26:10] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.2.0.201612012154 (Agent Core 3.1.0)
[08/27/17 16:26:11] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
2017-08-27T23:26:11.014Z pid:7588 worker:0 INFO supervisor starting (pid 7588)
2017-08-27T23:26:11.018Z pid:7588 worker:0 INFO supervisor reporting metrics to `internal:`
2017-08-27T23:26:11.046Z pid:7588 worker:0 INFO supervisor size set to undefined
2017-08-27T23:26:11.424Z pid:3608 worker:1 [08/27/17 16:26:11] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.2.0.201612012154 (Agent Core 3.1.0)
2017-08-27T23:26:11.503Z pid:3608 worker:1 [08/27/17 16:26:11] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
2017-08-27T23:26:12.550Z pid:3608 worker:1 [apim-lite][info] Starting DataPower API Gateway on port "4001"
2017-08-27T23:26:12.551Z pid:3608 worker:1 [apim-lite][info] Loading project "Local_API's" from "C:\Sunny\API-Connect-Research\Local_API's"
2017-08-27T23:26:13.225Z pid:3608 worker:1 [apim-lite][error] "docker info" exited with non-zero status: 1
2017-08-27T23:26:13.225Z pid:3608 worker:1 [apim-lite][info] Stopping DataPower API Gateway for project "Local_API's"
2017-08-27T23:26:15.250Z pid:7588 worker:0 ERROR supervisor worker id 1 (pid 3608) expected exit with 1

**Comment by yahelnachum** [comment]
Hello @sunnygoel8,

Thank you for raising this issue. I have tried to recreate this issue on a local environment, and so far I have been unsuccessful. Would you be able to provide us with more detailed information about your environment? If so could you tell us the following:
1. What version of Windows are you encountering this issue on (i.e. Windows 10, Windows 8.1 , Windows 8, Windows 7, etc.)?
2. What Docker program(s) do you have installed (i.e. Docker Toolbox, Docker for Windows, both)?
3. What version of the API Designer are you using?

**Comment by sunnygoel8** [comment]
Hi @yahelnachum ,

Thanks for your response. Here're the details.

Windows 10 Enterprise 2015 LTSB (doesn't support Docker for windows)
Docker Toolbox
5.0.7.2

**Comment by yahelnachum** [comment]
Hello @sunnygoe18,

Thanks for the additional information. I was able to recreate your issue when I ran `apic edit` from the Git Bash and tried to start the gateway. I solved this problem by running `apic edit` in the Docker Quickstart Terminal and then running the gateway. Please make sure your VirtualBox VM, that Docker Toolbox uses, has at least 4Gb of RAM and 2 CPUs available to it before trying to start the gateway. Please tell me if these instructions solved your issue.

**Comment by sunnygoel8** [comment]
Thanks @yahelnachum . It works fine when i run "apic edit" in Docker Quickstart Terminal but fails from local Command Line or Git Bash. Is it a known issue ?

Btw, I could see following containers running on docker host but facing issue in testing the api.

981e1d5c7281        ibm-apiconnect-toolkit/datapower-api-gateway-v6:1.0.10     "/bin/drouter"           About a minute ago   Up About a minute             0.0.0.0:32771->80/tcp, 0.0.0.0:32770->5554/tcp, 0.0.0.0:32769->9090/tcp, 0.0.0.0:4001->9443/tcp   localapis_datapower-api-gateway_1
2558690c210a        ibm-apiconnect-toolkit/datapower-gateway-director:1.0.10   "node lib/gateway-..."   About a minute ago   Up About a minute             0.0.0.0:32768->2443/tcp                                                                           localapis_datapower-gateway-director_1

As per above setup, IMO 4001 port on docker host should be mapped to 9443 on API Gateway. Am i correct? If so, I didn't see that port in "TCP Port Status" on web GUI. 

Tried testing API with 127.0.0.1 & 192.168.99.100 (Docker host IP) but facing connection issue. Can you please let me know what am I missing here ?

$ curl https://127.0.0.1:4001/api/current -H "X-IBM-Client-Id: default" -k
curl: (7) Failed to connect to 127.0.0.1 port 4001: Connection refused

$ curl https://192.168.99.100:4001/api/current -H "X-IBM-Client-Id: default" -k
curl: (7) Failed to connect to 192.168.99.100 port 4001: Connection refused

**Comment by yahelnachum** [comment]
Hello @sunnygoel8,

I'm glad that the proposed solution worked for you. 

> Is it a known issue ?

That's a good question.  I can investigate our code more.  Beyond that, I'm not an expert on `docker` but from searching the web it seems that this might be a known issue out there.  See for example https://github.com/docker/toolbox/issues/484

In terms of your curl request, if you are using the default settings you will need to add a header for the client secret. Your request should look like this then:
```
$ curl https://127.0.0.1:4001/api/current -H "x-ibm-client-id: default" -H "x-ibm-client-secret: SECRET" -k
```
Please refer to the following link for another example (https://developer.ibm.com/apiconnect/getting-started/run-your-api/).

**Comment by sunnygoel8** [comment]
Hi @yahelnachum , 

I'm still facing following issue while testing api. looked at **.datastore** file in directory from where i'm running apic edit command. Could see following entry there.

{"snapshot":"C:\\Sunny\\API-Connect-Research\\Local-APIs","host":"127.0.0.1","port":51410,"datapower":true}

**Error**

$ curl https://127.0.0.1:4001/api/current -H "x-ibm-client-id: default" -H "x-ibm-client-secret: SECRET" -k
curl: (7) Failed to connect to 127.0.0.1 port 4001: Connection refused

When used port 51410 instead of 4001, getting following SSL error.

$ curl https://127.0.0.1:51410/api/current -H "x-ibm-client-id: default" -H "x-ibm-client-secret: SECRET" -k
curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:51410

Moreover, I don't see any API operations in Explore tab in API designer. Any idea ?

**Comment by yahelnachum** [comment]
I'm sorry that didn't work for you.  Is it possible that you could attach or point to a project folder that I could use to try to reproduce the behavior you're seeing?

**Comment by sunnygoel8** [comment]
@yahelnachum , Possible for you to get on a call to look into this issue ? Attached the folder also. 

[Local-APIs.zip](https://github.com/ibm-apiconnect/apigateway-experimental/files/1271460/Local-APIs.zip)

**Comment by tonyffrench** [comment]
@johnbellessa is there anything you can glen from the comments above? Will the new prerequisite checker/helper better identify this failure scenario?

**Comment by yahelnachum** [comment]
Hello @sunnygoel8,

I was able to get the `curl` command to succeed. The steps I followed are:
1. Rename `weather_1.0.0.yaml` to `weather.yaml`.
2. Create a new product and give it a name. I named it `weather`.
3. Add the weather api to the weather product you just created.

Now all you should have to do is start the containers with the play button and issue your `curl` commands.

**Comment by sunnygoel8** [comment]
@yahelnachum , I tried what you suggested but I'm still getting the connection issue when testing with port 4001 and localhost (127.0.0.1)

As stated earlier, when container starts, it creates a .datastore file in same directory from where I issued the "apic edit" command. I do see a different port in that file.  Here're the contents of that file.

{"snapshot":"C:\\Sunny\\API-Connect-Research\\Local-APIs","host":"127.0.0.1","port":55300,"datapower":true}

When I test with port 55300, I get following error (Not the connection issue). Is it possible for you to get on a call & look into this issue ? Thanks.

curl: (35) Unknown SSL protocol error in connection to 127.0.0.1:55300

**Comment by yahelnachum** [comment]
Hello @sunnygoel8,

The port in your `.datastore` file is not the port that your `curl` command should be issued on. Please try issuing the `curl` command on the host and port shown on the bottom of the `APIC Designer` window near the `Gateway:` text. Make sure it's the `Gateway:` one and not the `Application:` one that might or might not be there.

Example of the `Gateway:` (address and port):
![bottom of apic designer](https://user-images.githubusercontent.com/7852732/30124714-0d3fed86-9304-11e7-85eb-d309d3332311.PNG)

**Comment by sunnygoel8** [comment]
@yahelnachum , I tried everything but no success..

**Comment by yahelnachum** [comment]
Hello @sunnygoel8,

Would it be possible for you to attach the logs of the Docker containers after you have launched the APIC Designer and submitted a `curl` request? If it is possible you should be able to run the following command in a second `Docker Quickstart Terminal` to grab each container and output the logs to separate files.
```
for c in $(docker ps | grep _datapower- | awk '{print $NF;}'); do docker logs $c > $c.log; done
```

**Comment by sunnygoel8** [comment]
![api designer_explore tab](https://user-images.githubusercontent.com/20052082/30340804-95a358fe-97a8-11e7-9f62-ac4ae38d5db4.JPG)

[localapis_datapower-api-gateway_1.txt](https://github.com/ibm-apiconnect/apigateway-experimental/files/1296894/localapis_datapower-api-gateway_1.txt)
[localapis_datapower-gateway-director_1.txt](https://github.com/ibm-apiconnect/apigateway-experimental/files/1296895/localapis_datapower-gateway-director_1.txt)

Hi @yahelnachum , 

Sorry for delay in response. Please see attached containers logs and API designer (Explore tab) screenshot. Here's my observation. 

1) Observed following issues in gateway log file. Not sure which plan & front-protocol is it referring to ?
I can see https protocol in swagger file & added API in plan as well inside Product.

    [0;31;1m20170912T173154.336Z [apiconnect][0x81000243][cli][error] : tid(36063): required property plan is missing
[0;31;1m20170912T173154.337Z [apiconnect][0x81000243][cli][error] : tid(36063): required property front-protocol is missing

2.) I don't see **Gateway:** & **Application:** rows in API designer when I started the gateway. Please see attached screenshot.

**Comment by sunnygoel8** [comment]
Hi @yahelnachum ,

Any update on this ? Did you get chance to go through the log files ?

**Comment by IgorBelyi** [comment]
@sunnygoel8 The errors in `localapis_datapower-api-gateway_1.txt` indicate that configuration compiled from your API yaml was incorrect. That may indicate either corrupted `apiconnect-config-to-datapower` package (dependency of apiconnect) or outdated docker images. Could you try reinstalling `apiconnect` (npm -g uninstall apiconnect; npm cache clear; npm install -g apiconnect) and then delete all `ibm-apiconnect-toolkit/datapower-*` docker images (using `docker rmi`) to allow toolkit to rebuild them on the next `apic start`?

**Comment by sunnygoel8** [comment]
Hi @IgorBelyi ,

I did what you asked me to. Now I'm getting following error in API Designer while starting the gateway.
Do you want me to install pm2 (npm install pm2 -g) and try again ? 

Error Starting Application


**Unable to start application. See below for more details.
Hide
      PM is not running**

**Comment by IgorBelyi** [comment]
OK, that's a tricky one. Could you try running 'LOG_LEVEL=debug apic start` from the command line? It should give more details of why PM (it has nothing to do with pm2 package) failed to start.

**Comment by sunnygoel8** [comment]
@IgorBelyi , I resolved PM issue by running following command - npm install pm2 -g

Btw, I'm still facing connection issue. Please see attached container logs for more details.

$ curl https://127.0.0.1:4001/api/current -H "x-ibm-client-id: default" -k
curl: (7) Failed to connect to 127.0.0.1 port 4001: Connection refused


[localapis_datapower-api-gateway_1.txt](https://github.com/ibm-apiconnect/apigateway-experimental/files/1304404/localapis_datapower-api-gateway_1.txt)
[localapis_datapower-gateway-director_1.txt](https://github.com/ibm-apiconnect/apigateway-experimental/files/1304403/localapis_datapower-gateway-director_1.txt)

**Comment by sunnygoel8** [comment]
@IgorBelyi , Noticed 1 more thing. Not sure, if its working as designed or there is an issue with this ?
For gateway container, port 4001 on docker host is mapped to port 9443 on DP. But when i looked at TCP Port list in DP GUI, there is no 9443 port  there. Why is it so ? 

70af676a22de        ibm-apiconnect-toolkit/datapower-api-gateway-v6:1.1.6     "/bin/drouter"           About an hour ago   Up About an hour    0.0.0.0:32779->80/tcp, 0.0.0.0:32778->5554/tcp, 0.0.0.0:32777->9090/tcp, 0.0.0.0:4001->9443/tcp   localapis_datapower-api-gateway_1

**Comment by IgorBelyi** [comment]
OK, so it's failing the same way now as it was doing before you reinstalled `apiconnect`.

Now, while container running could you get to its admin console. In `docker ps` output for localapis_datapower-api-gateway_1` look for mapping of the port `9090` (ex. `0.0.0.0:33012->9090/tcp`) the use the port on the left to get to the console (ex. http://127.0.0.1:33012 ), use `admin/admin` credentials and `apiconnect` domain to login. If that also gives you 'Connection refused', try changing `127.0.0.1` in that URL to the IP of the Docker host (ex. 192.168.99.100). After you login check that you have `tkgw` service up and running and listening on port `9443`.

![image](https://user-images.githubusercontent.com/5543754/30460730-a1f74950-9986-11e7-8ee4-eb30e48049c9.png)

If it's up and green that means the problem is in docker port forwarding. If it's marked with error please send us the generated config file. It can be found at _Administration/Main/File Management_ in `local:/apic-dev.cfg` file (the the file error message is referring to).

**Comment by IgorBelyi** [comment]
@sunnygoel8 OK, just noticed your second message. Yes, missing port 9443 in the list is another hint that `tkgw` service is broken. It also means you can get to DP GUI just fine - try to get the `local:apid-dev.cfg` file to us.

**Comment by sunnygoel8** [comment]
Hi @IgorBelyi ,

Please see attached apic-dev.cfg(changed extension to .txt) file and let me know how can we fix this ? I don't see tkgw service on box. 

[apic-dev.txt](https://github.com/ibm-apiconnect/apigateway-experimental/files/1305017/apic-dev.txt)

**Comment by IgorBelyi** [comment]
OK, so your `apic-dev.cfg` looks exactly how it would look if `apic` didn't find a single API in your project. Another hint that it's the case is `localapis_datapower-gateway-director_1.txt` not having a line `Loading project artifact weather_1.0.0.yaml`.

Could you show what `docker inspect localapi_datapower-gateway-director_1` returns? It should have a mount for you project's directory to `/tmp/project` inside the container and "CONFIG_DIR=/tmp/project" env. var.

Also, check if `docker exec localapi_datapower-gateway-director_1 ls /tmp/project` shows your `weather_1.0.0.yaml` file.

If that is all in order I'll try to find somebody tomorrow with more experience with Docker Toolbox on Windows 10 to see if they know why `datapower-gateway-director` may fail to find API yaml files on a mounted volume.

**Comment by sunnygoel8** [comment]
Hi @IgorBelyi , Please see attached docker inspect command output. I can see a mount for my project directory to /tmp/project and "CONFIG_DIR=/tmp/project" environment variable..

But when I tried accessing /tmp/project directory on docker host, I noticed that **project directory doesn't even exist in /tmp directory**. 

I stopped the gateway, manually created project folder in temp directory on my local machine. Copied API yaml file in project folder. Restarted gateway in API designer but still no success. 

[docker inspect_Output.txt](https://github.com/ibm-apiconnect/apigateway-experimental/files/1305230/docker.inspect_Output.txt)

**Comment by IgorBelyi** [comment]
Just to point out - it's not a directory on `docker host`, it's a mount point on a `docker container` named `localapi_datapower-gateway-director_1`. The `docker exec` command I mentioned above executes 'ls /tmp/project` inside the container to check if it was mounted properly there.

**Comment by sunnygoel8** [comment]
Yes, I understand that it's not a directory on docker host. But as per my understanding /tmp mount maps to following absolute path on my local machine. Please correct me If i am wrong

**C:\Users\sunny.goel\AppData\Local\Temp**

After starting gateway in API designer, I executed ls command on /tmp mount and didn't see project there. Is this a known issue?

**Comment by IgorBelyi** [comment]
Not quite. `/tmp/` is not mounted at all - it is local to the container. But if you look at the docker inspect_Output.txt you will see that among other Mounts there is this entry:
```
            {
                "Type": "bind",
                "Source": "/c/Sunny/API-Connect-Research/Local-APIs",
                "Destination": "/tmp/project",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
```
Which says that local directory */c/Sunny/API-Connect-Research/Local-APIs* is mounted as */tmp/project* in the container.

**Comment by sunnygoel8** [comment]
Got it. But when I ran the 2nd command provided by you, it didn't return anything. 

docker exec localapi_datapower-gateway-director_1 ls /tmp/project

**Comment by IgorBelyi** [comment]
Right, and that's the cause of the problem. I suspect (though not sure) that `/c/Sunny/API-Connect-Research/Local-APIs` path somehow fails to be interpreted the same as `C:\Sunny\API-Connect-Resource\Local-APIs`. But just to be sure could you check that you indeed have files in that location locally?

**Comment by sunnygoel8** [comment]
Hi @IgorBelyi , Even I do feel that path translation may cause the issue. 

Yes, I double checked and have all files in location locally. I do issue apic edit command from same folder on Docker QuickStart terminal & see the API in API Designer.

**Comment by sunnygoel8** [comment]
@IgorBelyi , Did you get chance to work with anyone in your team to resolve this issue ?

**Comment by IgorBelyi** [comment]
@sunnygoel8 Sorry. Yes, I've got a bit more suggestions. One suggestion was to try using directory in `C:\Users\sunny.goel` since docker deamon could be restricted to have access only to that location.

Also, you can try to check your Docker ability to mount local directories without use of `apic`. Try running:
`docker run --rm -v /c/Sunny/API-Connect-Research/Local-APIs:/tmp/project busybox ls /tmp/project`
That would use a very slim `busybox` container with mounted your project directory as `/tmp/project` so that you can see if there's any file. After that try
`docker run --rm -v /c/Users/sunny.goel:/tmp/project busybox ls /tmp/project`
The first one should show an empty directory as you already found out but if second one shows files in our home directory then moving your project under your home directory should work for `apic` as well.

**Comment by IgorBelyi** [comment]
@sunnygoel8 So, did moving project directory work?

**Comment by sunnygoel8** [comment]
Hi @IgorBelyi , I didn't try with moving project directory yet.

I first thought of running DP gateway on docker in regular (webapi and webapi-internal MPG in apiconnect domain) fashion instead of exploring experimental gateway features. There too, when i tried testing API, I'm getting following error. 

20171004T162458.141Z [apiconnect][0x80000001][apiconnect][error] mpgw(webapi): tid(34560)[request][192.168.99.1] gtid(1fdbc6c559d50b5a00008700): catalog not found: toolkit; env: apic-dev
20171004T162458.141Z [apiconnect][0x80000001][xsltmsg][error] mpgw(webapi): tid(34560)[request][192.168.99.1] gtid(1fdbc6c559d50b5a00008700): HTTP/1.1 404 Not Found:
20171004T162458.141Z [apiconnect][0x80c00010][xslt][error] mpgw(webapi): tid(34560)[request][192.168.99.1] gtid(1fdbc6c559d50b5a00008700): Processing of 'local:///isp/unified-request-select-and-set-tenant.xsl' stopped: local:///isp/error_template.xsl:85: xsl:message terminate=yes value='HTTP/1.1 404 Not Found: '

**Comment by IgorBelyi** [comment]
@sunnygoel8 The problem you have is Docker related, so you will have the same problem with anything depending on local directories being mounted in a container. When you use `apiconnect` either with regular or experimental DP it will require local project directory to be available in a container. In short, while you have a problem listing your project files by running `docker run --rm -v <your-project-dir>:/tmp/project busyboxy ls /tmp/project` you will have problems with using `apiconnect`.

**Comment by sunnygoel8** [comment]
@IgorBelyi : I moved project directory in folder where docker daemon is running. And I'm able to test API's successfully on my local machine using DP gateway running on Docker. Thanks for all your help.
