### ISSUE TITLE
Question:   Is there an IBM Roadmap for containerized API-Gateway

### ISSUE THREAD

**Issue by JulieBurkett** [ibm-apiconnect/apigateway-experimental#29]
Greetings,

Is there an IBM Roadmap that targets an enterprise ready (and supported) API-C Managed containerized API Gateway?

Thank you,

Julie

**Comment by mmatsa** [comment]
@JulieBurkett - A couple of clarifying questions:

- Are you asking about only the Gateway running in a container or also the Manager running in a container?
- Are you asking for a roadmap for the new `experimental` gateway or just any API Gateway at all?

**Comment by JulieBurkett** [comment]
@mmatsa - Clarification

Thank you for your response.  I'm asking about only the API Gateway (as in containerized datapower that can be managed by API-C Manager running on your standard OVA).

**Comment by mmatsa** [comment]
@JulieBurkett - Thanks.  If I'm understanding your request correctly, it's already supported and being used, for example by those using APIC Management nodes managing API Gateways running in the cloud using DataPower for Docker.

API Connect (API Mgr + Dev Portal) on-premise supporting API Gateways in the public cloud and on-premise is **supported today** and we have customers using that topology.  In this setup, all components are client managed.
