### ISSUE TITLE
datapower-gateway-director constantly restarting and eventually fails

### ISSUE THREAD

**Issue by smohith** [ibm-apiconnect/apigateway-experimental#34]
ibm@ibm-vm:~/apigateway$ docker ps
CONTAINER ID        IMAGE                                                      COMMAND                  CREATED             STATUS                          PORTS                                                                                             NAMES
a61929a81f89        ibm-apiconnect-toolkit/datapower-api-gateway-v6:1.0.10     "/bin/drouter"           7 minutes ago       Up 7 minutes                    0.0.0.0:32771->80/tcp, 0.0.0.0:32770->5554/tcp, 0.0.0.0:32769->9090/tcp, 0.0.0.0:4001->9443/tcp   apigateway_datapower-api-gateway_1
c9848a97da56        ibm-apiconnect-toolkit/datapower-gateway-director:1.0.10   "node lib/gateway-..."   7 minutes ago       Restarting (1) 32 seconds ago                                                                                                     apigateway_datapower-gateway-director_1
ibm@ibm-vm:~/apigateway$ apic services
Service apigateway-gw failed to start.

**Comment by IgorBelyi** [comment]
@smohith Please, provide output of the `docker logs apigateway_datapower-gateway-director_1`

**Comment by smohith** [comment]
@IgorBelyi Step 3 "apic config:set datapower-api-gateway-experimental=true" in the lab instructions can now be skipped as the dockerized DataPower API gateway is now integrated with the APIC Toolkit 5.0.7+ and no longer experimental. After I did that all was good.
